version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 10

  build:
    commands:
      - npm install
      - aws cloudformation package --template-file sam.yaml --s3-bucket ${S3_BUCKET}/augmentt-backend --output-template lambda.yaml

artifacts:
  files:
    - lambda.yaml
